spring.application.name=events
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:test}
spring.cloud.aws.sqs.endpoint=${SQS_ENDPOINT:http://localhost:4566}
spring.cloud.aws.sqs.queue=${SQS_AUTORIZADOR_EVENTOS_QUEUE_URL:sqs-autorizador-eventos}
spring.cloud.aws.dynamodb.endpoin=${DYNAMODB_ENDPOINT:http://localhost:4566}
